/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.dde.online.accounts.notify.xml -a doa_notify_adapter -p doa_notify_proxy
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DOA_NOTIFY_PROXY_H
#define DOA_NOTIFY_PROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <QTcpSocket>
#include <QNetworkAccessManager>
#include <QNetworkConfigurationManager>

class DoaNotifyProxy : public QObject
{
    Q_OBJECT
public:
    explicit DoaNotifyProxy(QObject *parent = nullptr);

    ~DoaNotifyProxy() override;

public slots: // METHODS
    //帐户信息
    void accountInfoNotify(const QString &IterfaceOper, const QString &accountInfo);
    //帐户状态
    void accountStateNotify(const QString &stateType, const QString &accountState);

    void netWorkStateNotify(const QNetworkConfiguration &config);

private:
    QTcpSocket *m_tcpSocket;

    QNetworkConfigurationManager *m_netManager;
};
#endif
