/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.dde.onlineaccount.calendar.xml -a doaaccountscalendar_adapter -c DOAAccountsCalendardapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "doaaccountscalendar_adapter.h"
#include "doaaccounts_adapter.h"

#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DOAAccountsCalendardapter
 */

DOAAccountsCalendardapter::DOAAccountsCalendardapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DOAAccountsCalendardapter::~DOAAccountsCalendardapter()
{
    // destructor
    qWarning() << "~DOAAccountsCalendardapter";
}

QString DOAAccountsCalendardapter::url() const
{
    // get the value of property url
    return qobject_cast<DOAAccountsadapter *>(parent())->getDoaProvider()->getUri();
}
