/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.dde.onlineaccount.calendar.xml -a doaaccountscalendar_adapter -c DOAAccountsCalendardapter
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DOAACCOUNTSCALENDAR_ADAPTER_H
#define DOAACCOUNTSCALENDAR_ADAPTER_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T>
class QList;
template<class Key, class Value>
class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.dde.onlineaccount.calendar
 */
class DOAAccountsCalendardapter : public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dde.onlineaccount.calendar")
public:
    DOAAccountsCalendardapter(QObject *parent);
    virtual ~DOAAccountsCalendardapter();

public: // PROPERTIES
    Q_PROPERTY(QString url READ url)
    QString url() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
